# server.toml
[server]
bind_addr = "0.0.0.0:2333" # `2333` specifies the port that rathole listens for clients

[server.services.terraria]
token = "<private_key>" # Token that is used to authenticate the client for the service. Change to an arbitrary value.
bind_addr = "0.0.0.0:7777" # `7777` specifies the port that exposes `terraria` to the Internet

