version: "3.9"
 
services:
  rathole-client:
    image: archef2000/rathole:latest
    restart: unless-stopped
    command: client
    environment:
      - "RUST_LOG=info"
      - "ADDRESS=${PROXY_ADDR}:2333"
      - "SERVICE_TOKEN_1=${RATHOLE_SERVICE_1_KEY}"
      - "SERVICE_NAME_1=terraria"
      - "SERVICE_ADDRESS_1=10.5.0.3:7777"
      - "SERVICE_TOKEN_2=${RATHOLE_SERVICE_23_KEY}"
      - "SERVICE_NAME_2=nginx_80"
      - "SERVICE_ADDRESS_2=10.5.0.5:80"
      - "SERVICE_TOKEN_3=${RATHOLE_SERVICE_23_KEY}"
      - "SERVICE_NAME_3=nginx_443"
      - "SERVICE_ADDRESS_3=10.5.0.5:443"
    networks:
      docker-net:
        ipv4_address: 10.5.0.2

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"    # HTTP
      - "443:443"  # HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-certs:/etc/nginx/certs:ro
    depends_on:
      - meme-drop
    restart: always
    networks:
      docker-net:
        ipv4_address: 10.5.0.5

  meme-drop:
    container_name: meme-drop 
    restart: unless-stopped
    build: 
      context: ./meme-drop
    image: host
    ports:
      - 3000:3000
    networks:
      docker-net:
        ipv4_address: 10.5.0.10

  terraria:
    image: ryshe/terraria:latest
    container_name: terraria
    restart: unless-stopped
    stdin_open: true # docker run -i
    tty: true # docker run -t
    environment:
      - WORLD_FILENAME=world.wld
      - CONFIGPATH=config.json
    networks:
      docker-net:
        ipv4_address: 10.5.0.3
    ports:
      - 7777:7777
    volumes:
      - ${PROJECT_DIR}/server/terraria:/root/.local/share/Terraria/Worlds

networks:
  docker-net:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
